# -*- coding: utf-8 -*-
"""🌐 Smart AI Translation Studio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLoT6J_XBl-Y06f1-JLs_X0yrUx6iFQx

# Developer Name: Rashid Ahmed
# Internship: CodeAlpha AI Internship
# Task: Task 01 – Language Translation Tool
# Technology: Python, Gradio, Deep Translator, LangDetect

# STEP 1 — Install Libraries
"""

!pip install gradio deep_translator langdetect

"""# STEP 2 — Import Libraries"""

import gradio as gr
from deep_translator import GoogleTranslator
from langdetect import detect, LangDetectException
from datetime import datetime

"""# STEP 3 — Language Dictionary"""

LANGUAGES = {
    "Auto Detect": "auto",
    "English": "en",
    "Urdu": "ur",
    "Arabic": "ar",
    "Hindi": "hi",
    "French": "fr",
    "German": "de",
    "Spanish": "es",
    "Italian": "it",
    "Chinese": "zh-CN",
    "Japanese": "ja",
    "Korean": "ko",
    "Russian": "ru",
    "Turkish": "tr",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Pashto": "ps"
}

language_names = list(LANGUAGES.keys())

"""# STEP 4 — Language Detection Function"""

def detect_lang(text):

    try:
        return detect(text)
    except LangDetectException:
        return "Unknown"

"""# STEP 5 — Translation Function"""

def translate_text(text, source, target):

    if not text.strip():
        return (
            "⚠ Please enter text.",
            "No language detected",
            "0 Characters"
        )

    try:

        source_code = LANGUAGES[source]
        target_code = LANGUAGES[target]

        detected = detect_lang(text)

        if source_code == "auto":
            source_code = detected

        translated = GoogleTranslator(
            source=source_code,
            target=target_code
        ).translate(text)

        stats = f"{len(text)} Characters"

        return (
            translated,
            f"Detected Language: {detected.upper()}",
            stats
        )

    except Exception as e:

        return (
            f"Error: {str(e)}",
            "Detection Failed",
            "0 Characters"
        )

"""# STEP 6 — Swap Function"""

def swap_languages(source, target):

    if source == "Auto Detect":
        source = "English"

    return target, source

"""# STEP 7 — Clear Function"""

def clear_fields():

    return (
        "",
        "",
        "",
        "0 Characters"
    )

"""# STEP 8 — Create Premium UI"""

with gr.Blocks(theme=gr.themes.Soft(), title="Smart AI Translation Studio") as app:
    # STEP 9: Custom Styling & Header
    gr.HTML("""
    <div style='text-align:center;'>
        <h1>🌐 Smart AI Translation Studio</h1>
        <h3>CodeAlpha Internship Task 01</h3>
        <p>Developed by <b>Rashid Ahmed</b></p>
    </div>
    """)

    # STEP 10: Language Selection Area
    with gr.Row():
        source_lang = gr.Dropdown(choices=language_names, value="Auto Detect", label="Source Language")
        target_lang = gr.Dropdown(choices=language_names, value="Urdu", label="Target Language")

    # STEP 11: Text Input Section
    input_text = gr.Textbox(lines=5, label="Enter Text", placeholder="Type text here...")

    # STEP 12: Action Buttons
    with gr.Row():
        translate_btn = gr.Button("🚀 Translate", variant="primary")
        swap_btn = gr.Button("🔄 Swap")
        clear_btn = gr.Button("🗑 Clear")

    # STEP 13 & 14: Output and Info Area
    output_text = gr.Textbox(lines=5, label="Translated Text", show_copy_button=True, interactive=False)
    with gr.Row():
        detected_language = gr.Textbox(label="Detected Language")
        statistics = gr.Textbox(label="Text Statistics")

    # STEP 15: Example Section
    gr.Examples(
        examples=[
            ["Hello World", "Auto Detect", "Urdu"],
            ["I love Artificial Intelligence", "Auto Detect", "Arabic"],
            ["میں پاکستان سے ہوں", "Auto Detect", "English"],
            ["Bonjour", "Auto Detect", "Spanish"]
        ],
        inputs=[input_text, source_lang, target_lang]
    )

    # STEP 16: Connect Button Logic
    translate_btn.click(
        fn=translate_text,
        inputs=[input_text, source_lang, target_lang],
        outputs=[output_text, detected_language, statistics]
    )

    swap_btn.click(
        fn=swap_languages,
        inputs=[source_lang, target_lang],
        outputs=[source_lang, target_lang]
    )

    clear_btn.click(
        fn=clear_fields,
        outputs=[input_text, output_text, detected_language, statistics]
    )

    # STEP 17: Footer
    gr.Markdown("""
    ---
    ### Features
    ✅ Automatic Language Detection | ✅ Google Translation | ✅ Modern UI | ✅ Copy Button | ✅ Translation Statistics
    """)

app.launch(debug=True)

"""# STEP 9 — Custom Styling"""

gr.HTML("""

    <div style='text-align:center;'>

    <h1>
    🌐 Smart AI Translation Studio
    </h1>

    <h3>
    CodeAlpha Internship Task 01
    </h3>

    <p>
    Developed by <b>Rashid Ahmed</b>
    </p>

    </div>

    """)

"""# STEP 11 — Text Input Section"""

input_text = gr.Textbox(
        lines=8,
        label="Enter Text",
        placeholder="Type text here..."
    )

"""# STEP 12 — Action Buttons"""

with gr.Row():

        translate_btn = gr.Button(
            "🚀 Translate",
            variant="primary"
        )

        swap_btn = gr.Button(
            "🔄 Swap"
        )

        clear_btn = gr.Button(
            "🗑 Clear"
        )

"""# STEP 13 — Output Area"""

output_text = gr.Textbox(
        lines=8,
        label="Translated Text",
        show_copy_button=True
    )

"""# STEP 14 — Information Cards"""

with gr.Blocks(theme=gr.themes.Soft(), title="Smart AI Translation Studio") as app:
    with gr.Row():
        detected_language = gr.Textbox(
            label="Detected Language"
        )
        statistics = gr.Textbox(
            label="Text Statistics"
        )

app.launch()

"""# STEP 15 — Example Section"""

gr.Examples(

        examples=[

            ["Hello World", "Auto Detect", "Urdu"],

            ["I love Artificial Intelligence",
             "Auto Detect",
             "Arabic"],

            ["میں پاکستان سے ہوں",
             "Auto Detect",
             "English"],

            ["Bonjour",
             "Auto Detect",
             "Spanish"]
        ],

        inputs=[
            input_text,
            source_lang,
            target_lang
        ]
    )